<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DosenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

     $dosenData=   DB::table('dosen')->insert([

            // [
            //     'user_id' => 4,
            //     'nidn' => '202407244',
            //     'nama_lengkap' => 'Sofyan Lukmanfiandy, S.Kom., M.Kom.',
            //     'prodi_id' => 1,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-03',
            //     'agama' => 'KRISTEN',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 5,
            //     'nidn' => '202407245',
            //     'nama_lengkap' => 'Eri Haryanto, S.Kom., M.Kom.',
            //     'prodi_id' => 1,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-04',
            //     'agama' => 'KATOLIK',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 6,
            //     'nidn' => '202407246',
            //     'nama_lengkap' => 'Agustin Setiyorini, S.Kom., M.Kom.',
            //     'prodi_id' => 1,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-05',
            //     'agama' => 'HINDU',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 7,
            //     'nidn' => '202407247',
            //     'nama_lengkap' => 'Jeffry Andhika Putra, S.T., M.M., M.Eng.',
            //     'prodi_id' => 1,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-06',
            //     'agama' => 'BUDHA',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 8,
            //     'nidn' => '202407248',
            //     'nama_lengkap' => 'Yumarlin MZ, S.Kom., M.Pd., M.Kom.',
            //     'prodi_id' => 1,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-07',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 9,
            //     'nidn' => '202407249',
            //     'nama_lengkap' => 'Ryan Ari Setyawan, S.Kom., M.Eng.',
            //     'prodi_id' => 1,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-08',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 10,
            //     'nidn' => '202407250',
            //     'nama_lengkap' => 'Erry Maricha Oki NH, S.Kom., MTA',
            //     'prodi_id' => 1,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-09',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 11,
            //     'nidn' => '202407251',
            //     'nama_lengkap' => 'Andreas Ronald Setianan, B.Bus., M.Comm',
            //     'prodi_id' => 2,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-10',
            //     'agama' => 'KRISTEN',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 12,
            //     'nidn' => '202407252',
            //     'nama_lengkap' => 'Angelia Pribadi, S.E., M.Sc, Ak',
            //     'prodi_id' => 2,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-11',
            //     'agama' => 'KATOLIK',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 13,
            //     'nidn' => '202407253',
            //     'nama_lengkap' => 'Dewi Puspitasari, S.E., M.Acc., Ak., CA.',
            //     'prodi_id' => 2,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-12',
            //     'agama' => 'HINDU',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 14,
            //     'nidn' => '202407254',
            //     'nama_lengkap' => 'Handoko Arwi Hasthoro, S.E., M.Si',
            //     'prodi_id' => 2,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-13',
            //     'agama' => 'BUDHA',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 15,
            //     'nidn' => '202407255',
            //     'nama_lengkap' => 'Vian Candra Wijaya, S.E., M.Pd',
            //     'prodi_id' => 2,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-14',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 16,
            //     'nidn' => '202407256',
            //     'nama_lengkap' => 'Gina Alviana, S.E., M.Kom.',
            //     'prodi_id' => 2,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-15',
            //     'agama' => 'KATOLIK',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 17,
            //     'nidn' => '202407257',
            //     'nama_lengkap' => 'Asep Haryanto, S.E., M.Sc.',
            //     'prodi_id' => 2,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-16',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 18,
            //     'nidn' => '202407258',
            //     'nama_lengkap' => 'Rina Ayu, S.E., M.Pd.',
            //     'prodi_id' => 2,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-17',
            //     'agama' => 'KRISTEN',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 19,
            //     'nidn' => '202407259',
            //     'nama_lengkap' => 'Yudi Setiawan, S.E., M.Kom.',
            //     'prodi_id' => 2,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-18',
            //     'agama' => 'BUDHA',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 20,
            //     'nidn' => '202407260',
            //     'nama_lengkap' => 'Nina Adriani, S.E., M.Ak',
            //     'prodi_id' => 3,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-19',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 21,
            //     'nidn' => '202407261',
            //     'nama_lengkap' => 'Bagus Pratama, S.T., M.Eng.',
            //     'prodi_id' => 3,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-20',
            //     'agama' => 'HINDU',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 22,
            //     'nidn' => '202407262',
            //     'nama_lengkap' => 'Sari Dewi, S.Kom., M.T.',
            //     'prodi_id' => 3,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-21',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 23,
            //     'nidn' => '202407263',
            //     'nama_lengkap' => 'Andi Rahman, S.Kom., M.Kom.',
            //     'prodi_id' => 3,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-22',
            //     'agama' => 'KATOLIK',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 24,
            //     'nidn' => '202407264',
            //     'nama_lengkap' => 'Tari Setiani, S.Kom., M.Kom.',
            //     'prodi_id' => 3,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-23',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 25,
            //     'nidn' => '202407265',
            //     'nama_lengkap' => 'Fajar Nugroho, S.T., M.Eng.',
            //     'prodi_id' => 3,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-24',
            //     'agama' => 'BUDHA',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 26,
            //     'nidn' => '202407266',
            //     'nama_lengkap' => 'Mita Utami, S.E., M.T.',
            //     'prodi_id' => 3,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-25',
            //     'agama' => 'HINDU',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 27,
            //     'nidn' => '202407267',
            //     'nama_lengkap' => 'Lina Yuliana, S.Kom., M.Eng.',
            //     'prodi_id' => 3,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-26',
            //     'agama' => 'KATOLIK',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 28,
            //     'nidn' => '202407268',
            //     'nama_lengkap' => 'Bambang Setiawan, S.T., M.Si.',
            //     'prodi_id' => 3,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-27',
            //     'agama' => 'ISLAM',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 29,
            //     'nidn' => '202407269',
            //     'nama_lengkap' => 'Susiwati, S.Kom., M.T.',
            //     'prodi_id' => 3,
            //     'gender' => 'Wanita',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-28',
            //     'agama' => 'HINDU',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            // [
            //     'user_id' => 30,
            //     'nidn' => '202407270',
            //     'nama_lengkap' => 'Arif Nurcahyo, S.Kom., M.Kom.',
            //     'prodi_id' => 3,
            //     'gender' => 'Pria',
            //     'tempat_lahir' => 'Berau',
            //     'tanggal_lahir' => '1999-08-29',
            //     'agama' => 'KATOLIK',
            //     'status_dosen' => 'AKTIF',
            //     'alamat' => 'JL. S.A Maulana',
            //     'telepon' => '88335566',
            // ],
            [
                'user_id' => 9,
                'nidn' => '202407241',
                'nama_lengkap' => 'Jemmy Edwin Bororing, S.Kom., M.Eng.',
                'prodi_id' => 1,
                'gender' => 'Pria',
                'tempat_lahir' => 'Berau',
                'tanggal_lahir' => '1999-07-31',
                'agama' => 'ISLAM',
                'status_dosen' => 'AKTIF',
                'alamat' => 'JL. S.A Maulana',
                'telepon' => '88335566',
            ],
            [
                'user_id' => 10,
                'nidn' => '202407242',
                'nama_lengkap' => 'Fatsyahrina Fitriastuti, S.Si., M.T.',
                'prodi_id' => 3,
                'gender' => 'Wanita',
                'tempat_lahir' => 'Berau',
                'tanggal_lahir' => '1999-08-01',
                'agama' => 'ISLAM',
                'status_dosen' => 'AKTIF',
                'alamat' => 'JL. S.A Maulana',
                'telepon' => '88335566',
            ],
            [
                'user_id' => 11,
                'nidn' => '202407243',
                'nama_lengkap' => 'Sri Rahayu, S.Kom., M.Eng.',
                'prodi_id' => 2,
                'gender' => 'Wanita',
                'tempat_lahir' => 'Berau',
                'tanggal_lahir' => '1999-08-02',
                'agama' => 'ISLAM',
                'status_dosen' => 'AKTIF',
                'alamat' => 'JL. S.A Maulana',
                'telepon' => '88335566',
            ]
        ]);

        DB::table('dosen')->insert($dosenData);

    }
}
